# Generated by Django 2.2.1 on 2019-06-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channelaudit', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='FaceSearchFiles')),
                ('first_look', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channelaudit.CaseProject')),
            ],
            options={
                'verbose_name': '人脸搜索',
                'verbose_name_plural': '人脸搜索',
            },
        ),
    ]
