# Generated by Django 2.2.1 on 2019-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channelaudit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenseID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30, unique=True)),
                ('token', models.TextField(blank=True, default='None')),
                ('token_time', models.CharField(blank=True, default='0', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channelaudit.CaseProject', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'SenseID_Token',
                'verbose_name_plural': 'SenseID_Token',
            },
        ),
    ]
