# Generated by Django 2.2.1 on 2019-06-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channelaudit', '0002_auto_20190623_1246'),
        ('senseid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senseid',
            name='project',
        ),
        migrations.AddField(
            model_name='senseid',
            name='project_device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channelaudit.CaseProjectDevice', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
