# Generated by Django 2.2.1 on 2019-06-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senseid', '0002_auto_20190623_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senseid',
            name='project_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channelaudit.CaseProjectDevice', verbose_name='对应设备'),
        ),
    ]
