# Generated by Django 2.2.1 on 2019-06-22 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('project_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='项目地址')),
                ('project_status', models.IntegerField(choices=[(1, '启用'), (2, '禁用')], default=1, verbose_name='项目状态')),
                ('group_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目GROUP_ID')),
                ('hard_dog_nums', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬狗序列号')),
                ('node_path_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='节点路径ID')),
                ('node_path_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='节点路径名称')),
                ('forward_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='??')),
                ('offline_notice_email', models.CharField(blank=True, max_length=32, null=True, verbose_name='离线告警邮箱')),
                ('offline_notice_mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='离线通知手机')),
                ('authorize_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='授权URL')),
                ('valid_date', models.DateTimeField(blank=True, null=True, verbose_name='项目有效期')),
                ('allot_user_type', models.IntegerField(choices=[(1, '遵循父节点'), (2, '自定义')], verbose_name='分配用户类型')),
                ('is_del', models.IntegerField(choices=[(0, '不删除'), (1, '删除')], default=0, verbose_name='是否删除')),
                ('create_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('update_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.CaseNode', verbose_name='节点ID')),
                ('sensetimeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SENSETIMEID', to='utils.SensetimeID', verbose_name='商汤秘钥')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
            },
        ),
        migrations.CreateModel(
            name='CaseProjectDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备ID')),
                ('device_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备名称')),
                ('device_type', models.IntegerField(blank=True, choices=[(1, '一体机'), (2, '摄像头'), (3, '前端服务器')], null=True, verbose_name='设备类型')),
                ('device_status', models.IntegerField(blank=True, choices=[(0, '正常'), (1, '离线')], null=True, verbose_name='设备状态')),
                ('is_del', models.IntegerField(choices=[(0, '不删除'), (1, '删除')], default=0, verbose_name='是否删除')),
                ('create_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('update_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channelaudit.CaseProject')),
            ],
            options={
                'verbose_name': '设备列表',
                'verbose_name_plural': '设备列表',
            },
        ),
    ]
