# Generated by Django 2.2.1 on 2019-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casechannel',
            name='brush_card_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='刷证时间'),
        ),
        migrations.AlterField(
            model_name='casechannel',
            name='first_look_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='首次带看时间'),
        ),
        migrations.AlterField(
            model_name='casechannel',
            name='report_time',
            field=models.IntegerField(verbose_name='报备时间'),
        ),
        migrations.AlterField(
            model_name='caseidentify',
            name='id_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='caseidentify',
            name='verify_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='认证时间'),
        ),
        migrations.AlterField(
            model_name='caseidentifyconfidence',
            name='first_snap_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='首次抓拍时间'),
        ),
        migrations.AlterField(
            model_name='caseidentifyconfidence',
            name='next_first_snap_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='获取到报备时间后(首次抓拍时间)'),
        ),
        migrations.AlterField(
            model_name='caseidentifyconfidence',
            name='second_snap_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='获取报备时间之前(第一个时间)'),
        ),
    ]
