# Generated by Django 2.2.1 on 2019-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190624_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casechannel',
            name='brush_card_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='刷证时间'),
        ),
        migrations.AlterField(
            model_name='casechannel',
            name='first_look_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='首次带看时间'),
        ),
        migrations.AlterField(
            model_name='casechannel',
            name='report_time',
            field=models.CharField(max_length=64, verbose_name='报备时间'),
        ),
        migrations.AlterField(
            model_name='casechannel',
            name='sign_time',
            field=models.DateTimeField(blank=True, max_length=64, null=True, verbose_name='签约时间'),
        ),
    ]
