# Generated by Django 2.2.1 on 2019-06-22 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ids', models.CharField(blank=True, max_length=128, null=True, verbose_name='父节点集合')),
                ('node_path_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='节点路径名称')),
                ('node_name', models.CharField(max_length=64, verbose_name='节点名称')),
                ('node_type', models.CharField(blank=True, choices=[('M', '集团'), ('F', '城市'), ('C', '区域'), ('X', '项目')], max_length=1, null=True, verbose_name='节点类型（M集团 C区域 F城市）')),
                ('node_status', models.IntegerField(blank=True, choices=[(1, '启用'), (2, '禁用')], null=True, verbose_name='状态')),
                ('node_level', models.IntegerField(blank=True, null=True, verbose_name='资源的级数，树状结构')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='节点图标')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('exists_avert_function', models.IntegerField(blank=True, choices=[(0, '存在规则'), (1, '没有规则')], default=1, null=True, verbose_name='是否有稽核规则')),
                ('avert_fly_sheet_audit_time', models.IntegerField(blank=True, choices=[(1, '报备时间'), (2, '首次带看时间')], null=True, verbose_name='防飞单稽核时间')),
                ('fly_sheet_audit_tolerance', models.IntegerField(blank=True, null=True, verbose_name='稽核时间容差，单位min')),
                ('avert_carrying_capacity_status', models.CharField(blank=True, choices=[('on', '开启'), ('off', '关闭')], max_length=4, null=True, verbose_name='防载客功能状态')),
                ('avert_carrying_capacity_tolerance', models.IntegerField(blank=True, null=True, verbose_name='防载客时间容差，单位min')),
                ('customer_protect_time', models.IntegerField(blank=True, null=True, verbose_name='客户保护时间')),
                ('is_del', models.IntegerField(choices=[(0, '不删除'), (1, '删除')], default=0, verbose_name='是否删除')),
                ('create_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('update_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.CaseNode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
    ]
