# Generated by Django 2.2.1 on 2019-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenode',
            name='avert_carrying_capacity_status',
            field=models.CharField(blank=True, choices=[('on', '开启'), ('off', '关闭')], default='off', max_length=4, null=True, verbose_name='防载客功能状态'),
        ),
        migrations.AlterField(
            model_name='casenode',
            name='customer_protect_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='客户保护时长（天）'),
        ),
        migrations.AlterField(
            model_name='casenode',
            name='node_status',
            field=models.IntegerField(choices=[(1, '启用'), (2, '禁用')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='casenode',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='node.CaseNode', verbose_name='父节点'),
        ),
    ]
