# Generated by Django 2.2.1 on 2019-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20190624_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casenode',
            name='avert_carrying_capacity_tolerance',
            field=models.IntegerField(default=30, verbose_name='防载客时间容差，单位min'),
        ),
    ]
